spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/phi_library?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true
  flyway:
    user: root
    password: root
    schemas: phi_library